name: helm bug

on:
  workflow_dispatch:

jobs:
  bug:
    strategy:
      fail-fast: false
      matrix:
        version: ["v3.12.3", "v3.13.0"]
    runs-on: ubuntu-latest
    steps:
    - uses: azure/setup-helm@v3
      with:
        version: ${{ matrix.version }}        
    - run: helm version
    - run: helm pull oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set --debug
